import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print("Sum:",np.sum(array))
print("Mean:",np.mean(array))
print("Minimum:",np.min(array))
print("Maximim:",np.max(array))
print("Std deviation:",np.std(array))
print("Variance:",np.var(array))
array_type =type(array)
print(array_type)
